app = "lavanda-menu"
primary_region = "fra"

[build]

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "suspend"
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type = "requests"
    soft_limit = 200
    hard_limit = 400

[checks]
  [checks.up]
    type = "http"
    port = 8080
    path = "/healthz"
    interval = "30s"
    timeout = "4s"
    grace_period = "10s"

[[vm]]
  memory = "512mb"
  cpu_kind = "shared"
  cpus = 1
